# Generated by Django 4.2.8 on 2023-12-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('num_to_english', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ConvertedNumber',
        ),
    ]
